# Generated by Django 3.0.3 on 2020-02-05 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguridad',
            name='email',
            field=models.CharField(max_length=120, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='seguridad',
            name='password',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
