# Generated by Django 3.0.3 on 2020-02-05 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200205_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguridad',
            name='email',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(regex='^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$')]),
        ),
    ]
