# Generated by Django 3.0.3 on 2020-02-05 21:22

import django.core.validators
from django.db import migrations, models
import login.validators


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200205_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguridad',
            name='password',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8), login.validators.validate_correct_password]),
        ),
    ]
