# Generated by Django 3.0.3 on 2020-02-08 02:06

from django.db import migrations, models
import login.validators


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200207_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguridad',
            name='email',
            field=models.CharField(max_length=120, unique=True, validators=[login.validators.validate_correct_email]),
        ),
    ]
